#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys, os
import sqlite3

if __name__ == '__main__':

    db_file = "statistics.db"

    #if os.path.exists(db_file):
    #    sys.exit("db already exists, exiting...")

    # Connect
    conn = sqlite3.connect(db_file)
    c = conn.cursor()

    # Drop
    # c.execute("DROP TABLE statistics")
    # c.execute("DROP TABLE computerSettings")
    #
    # # Create the "statistic" table
    # c.execute("CREATE TABLE statistics (id int PRIMARY KEY, userName varchar(100), dayTime varchar(100), userStatus varchar(100), winner varchar(100))")
    # c.execute("CREATE TABLE computerSettings (id int, color varchar(100), difficulty varchar(100), sadism varchar(100), FOREIGN KEY(id) REFERENCES statistics(id))")
    #
    #
    # # Insert records
    # c.execute("INSERT INTO statistics (id, userName, dayTime, userStatus, winner) VALUES (1, 'Lindsay', 'April_12_2018', 'win', 'Lindsay')")
    # c.execute("INSERT INTO statistics (id, userName, dayTime, userStatus, winner) VALUES (2, 'Lindsay', 'April_13_2018', 'lose', 'green')")
    # c.execute("INSERT INTO statistics (id, userName, dayTime, userStatus, winner) VALUES (3, 'Peter', 'April_14_2018', 'quit', Null)")
    # c.execute("INSERT INTO statistics (id, userName, dayTime, userStatus, winner) VALUES (4, 'Yujia', 'April_15_2018', 'win', 'Yujia')")
    #
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (1, 'green', 'skilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (1, 'yellow', 'unskilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (2, 'blue', 'skilled', 'mean')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (2, 'green', 'skilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (2, 'red', 'skilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (3, 'blue', 'skilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (3, 'red', 'skilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (4, 'yellow', 'skilled', 'nice')")
    # c.execute("INSERT INTO computerSettings (id, color, difficulty, sadism) VALUES (4, 'green', 'skilled', 'nice')")
    #
    #
    # # Save updates
    # conn.commit()

    # for row in c.execute("SELECT * from statistics"):
    #     print(row)
    #
    # for row in c.execute("SELECT * from computerSettings"):
    #     print(row)

    for row in c.execute("SELECT * FROM statistics"):
        print(row)


    # Delete records
    def delete():
        c.execute("DELETE FROM training_data where txt = 'hellp'")


    # close it up:
    conn.close()
